name: Deploy to Firebase Hosting
on:
  push:
    branches:
      - dev
jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout repo
        uses: actions/checkout@dev
      - name: Install dependencies
        uses: npm install
      - name: Build
        uses: npm run build
      - name: Archive production
        uses: actions/upload-artifact@master
        with:
          name: build
          path: build
  deploy:
    name: Deploy
    needs: build
    runs-on: ubunut-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@dev
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env: 
          FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
